CREATE SCHEMA IF NOT EXISTS TODO;

DROP TABLE IF EXISTS TODO.TITU;
DROP TABLE IF EXISTS TODO.COORDINADOR;
DROP TABLE IF EXISTS TODO.COORDINADOR_TITTU;
DROP TABLE IF EXISTS TODO.COORDINADOR_ALL;
DROP TABLE IF EXISTS TODO.TRIBUNAL;

CREATE TABLE TODO.TITU (
		cod_titu VARCHAR(3) NOT NULL,
		tipo_titulacion VARCHAR(1) NOT NULL,
		curso_aca INTEGER NOT NULL
		--CONSTRAINT CONSTRAINT_PK_TITU PRIMARY KEY (cod_titu, tipo_titulacion, curso_aca)
	);

CREATE TABLE TODO.COORDINADOR (
		email VARCHAR(500) NOT NULL,
		nombre VARCHAR(82) NOT NULL
	);


CREATE TABLE TODO.COORDINADOR_TITU (
		cod_titu VARCHAR(3) NOT NULL,
		tipo_titulacion VARCHAR(1) NOT NULL,
		curso_aca INTEGER NOT NULL,
		email VARCHAR(500) NOT NULL
		--CONSTRAINT CONSTRAINT_PK_COORDINADOR PRIMARY KEY (cod_titu, tipo_titulacion, curso_aca, email)
	);

CREATE TABLE TODO.COORDINADOR_ALL (
		cod_titu VARCHAR(3) NOT NULL,
		tipo_titulacion VARCHAR(1) NOT NULL,
		curso_aca INTEGER NOT NULL,
		email VARCHAR(500) NOT NULL,
		nombre VARCHAR(82) NOT NULL
		--CONSTRAINT CONSTRAINT_PK_COORDINADOR PRIMARY KEY (cod_titu, tipo_titulacion, curso_aca, email)
	);


CREATE TABLE TODO.TRIBUNAL(
		user_id VARCHAR(8) NOT NULL,
		curso_aca INTEGER NOT NULL,
		cod_conv_defensa VARCHAR(1) NOT NULL,
		convocatoria VARCHAR(10) NOT NULL,
		cod_titu VARCHAR(3) NOT NULL,
		tipo_titulacion VARCHAR(1) NOT NULL,
		tipo_tribunal VARCHAR(2) NOT NULL,
		descripcion VARCHAR(150) NOT NULL,
		fecha_presentacion TIMESTAMP
		--CONSTRAINT CONSTRAINT_PK_TRIBUNAL PRIMARY KEY (user_id, cod_titu, tipo_titulacion, curso_aca)
	);

